# Generated by Django 5.2.7 on 2025-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_alter_transactions_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
